# Minecraft version(s)
additional_versions=1.16.5,1.17,1.17.1

# Forge
forge_loader=[36,)
forge_version=1.16.5-36.2.42

# Fabric
yarn_mappings=1.16.5+build.10
loader_version=0.19.2
fabric_version=0.42.0+1.16

# NeoForge
#yarn_mappings_neoforge_patch=
#neoforge_version=
