# Minecraft version(s)
additional_versions=1.18,1.18.1,1.18.2

# Forge
forge_loader=[38,)
forge_version=1.18-38.0.17

# Fabric
yarn_mappings=1.18+build.1
loader_version=0.19.2
fabric_version=0.44.0+1.18

# NeoForge
#yarn_mappings_neoforge_patch=
#neoforge_version=
