# Minecraft version(s)
additional_versions=1.21.11

# Forge
forge_loader=[61,)
#forge_version=1.21.11-61.1.5

# Fabric
yarn_mappings=1.21.11+build.4
loader_version=0.19.2
fabric_version=0.140.2+1.21.11

# NeoForge
yarn_mappings_neoforge_patch=1.21+build.6
neoforge_version=21.11.24-beta
