# Minecraft version(s)
additional_versions=26.1.1

# Forge
forge_loader=[62,)
#forge_version=1.21.11-63.0.2

# Fabric
#yarn_mappings=
loader_version=0.19.2
fabric_version=0.145.4+26.1.1

# NeoForge
#yarn_mappings_neoforge_patch=
neoforge_version=26.1.1.15-beta
