# Minecraft version(s)
additional_versions=26.1

# Forge
forge_loader=[62,)
#forge_version=1.21.11-62.0.9

# Fabric
#yarn_mappings=
loader_version=0.19.2
fabric_version=0.145.1+26.1

# NeoForge
#yarn_mappings_neoforge_patch=
neoforge_version=26.1.0.19-beta
